runtime: python39

# 🚀 Increase the instance size to fix memory issue
instance_class: F2

# ✅ Entry point for your Flask app (file is App.py and Flask app is named 'app')
entrypoint: gunicorn -b :$PORT App:app

# ✅ Allow all URLs to be handled by the Flask app
handlers:
- url: /.*
  script: auto
